#!/bin/bash

# 3D Gaussian Splatting 运行示例脚本
# 展示如何使用本工程中的脚本进行训练和测试

echo "=========================================="
echo "3D Gaussian Splatting 运行示例"
echo "=========================================="
echo ""

# 给脚本添加执行权限
echo "1. 给脚本添加执行权限..."
chmod +x setup_and_test.sh train_model.sh

echo ""
echo "2. 运行环境设置脚本..."
echo "   ./setup_and_test.sh"
echo ""
echo "   或者手动设置环境:"
echo "   conda activate gaussian_splatting"
echo "   export CC=/usr/bin/gcc"
echo "   export CXX=/usr/bin/g++"
echo "   export CUDAHOSTCXX=/usr/bin/g++"

echo ""
echo "3. 示例训练命令:"
echo ""
echo "   a) 快速测试 (100次迭代):"
echo "      ./train_model.sh -d assets/tandt_db/tandt/train -i 100"
echo ""
echo "   b) 完整训练 Tanks&Temples train 场景 (30,000次迭代):"
echo "      ./train_model.sh -d assets/tandt_db/tandt/train -m tandt_train --eval"
echo ""
echo "   c) 训练 Tanks&Temples truck 场景:"
echo "      ./train_model.sh -d assets/tandt_db/tandt/truck -m tandt_truck -i 30000 --eval"
echo ""
echo "   d) 训练 Deep Blending drjohnson 场景 (白色背景):"
echo "      ./train_model.sh -d assets/tandt_db/db/drjohnson -m db_drjohnson --eval --white-bg"
echo ""
echo "   e) 使用加速优化器训练:"
echo "      ./train_model.sh -d assets/tandt_db/tandt/train -m accelerated --accelerated"
echo ""
echo "   f) 低VRAM配置训练 (8GB GPU):"
echo "      ./train_model.sh -d assets/tandt_db/tandt/train -m low_vram -g 8 -i 15000"

echo ""
echo "4. 手动训练命令示例:"
echo ""
echo "   a) 基础训练:"
echo "      python train.py -s assets/tandt_db/tandt/train"
echo ""
echo "   b) 带评估的训练:"
echo "      python train.py -s assets/tandt_db/tandt/train --eval"
echo ""
echo "   c) 指定输出目录:"
echo "      python train.py -s assets/tandt_db/tandt/train -m my_output"
echo ""
echo "   d) 使用加速优化器:"
echo "      python train.py -s assets/tandt_db/tandt/train --optimizer_type sparse_adam"
echo ""
echo "   e) 启用抗锯齿:"
echo "      python train.py -s assets/tandt_db/tandt/train --antialiasing"

echo ""
echo "5. 渲染和评估命令:"
echo ""
echo "   a) 渲染训练好的模型:"
echo "      python render.py -m output/<模型目录>"
echo ""
echo "   b) 计算评估指标:"
echo "      python metrics.py -m output/<模型目录>"
echo ""
echo "   c) 跳过训练集渲染:"
echo "      python render.py -m output/<模型目录> --skip_train"
echo ""
echo "   d) 跳过测试集渲染:"
echo "      python render.py -m output/<模型目录> --skip_test"

echo ""
echo "6. 可视化命令:"
echo ""
echo "   a) 构建 SIBR 查看器:"
echo "      cd SIBR_viewers"
echo "      cmake -Bbuild ."
echo "      cmake --build build --target install --config RelWithDebInfo"
echo ""
echo "   b) 实时训练可视化:"
echo "      # 终端1: python train.py -s <数据集> --ip 127.0.0.1 --port 6009"
echo "      # 终端2: ./SIBR_viewers/install/bin/SIBR_remoteGaussian_app"
echo ""
echo "   c) 查看训练好的模型:"
echo "      ./SIBR_viewers/install/bin/SIBR_gaussianViewer_app -m output/<模型目录>"

echo ""
echo "7. 处理自己的图像:"
echo ""
echo "   a) 准备图像:"
echo "      mkdir -p my_dataset/input"
echo "      cp your_images/*.jpg my_dataset/input/"
echo ""
echo "   b) 运行转换脚本:"
echo "      python convert.py -s my_dataset --resize"
echo ""
echo "   c) 训练自定义数据集:"
echo "      python train.py -s my_dataset"

echo ""
echo "8. 完整工作流程示例:"
echo ""
echo "   # 1. 激活环境"
echo "   conda activate gaussian_splatting"
echo ""
echo "   # 2. 设置编译器"
echo "   export CC=/usr/bin/gcc"
echo "   export CXX=/usr/bin/g++"
echo "   export CUDAHOSTCXX=/usr/bin/g++"
echo ""
echo "   # 3. 快速测试训练"
echo "   ./train_model.sh -d assets/tandt_db/tandt/train -i 1000 -m quick_test"
echo ""
echo "   # 4. 完整训练"
echo "   ./train_model.sh -d assets/tandt_db/tandt/train -m full_training --eval"
echo ""
echo "   # 5. 渲染结果"
echo "   python render.py -m output/full_training_*"
echo ""
echo "   # 6. 评估指标"
echo "   python metrics.py -m output/full_training_*"

echo ""
echo "9. 故障排除:"
echo ""
echo "   a) CUDA扩展编译失败:"
echo "      export CC=/usr/bin/gcc"
echo "      export CXX=/usr/bin/g++"
echo "      export CUDAHOSTCXX=/usr/bin/g++"
echo ""
echo "   b) VRAM不足:"
echo "      # 降低分辨率"
echo "      python train.py -s <数据集> -r 2"
echo ""
echo "      # 使用CPU存储数据"
echo "      python train.py -s <数据集> --data_device cpu"
echo ""
echo "      # 减少迭代次数"
echo "      python train.py -s <数据集> --iterations 7000"
echo ""
echo "   c) 查看帮助:"
echo "      ./train_model.sh --help"
echo "      python train.py --help"
echo "      python render.py --help"
echo "      python metrics.py --help"

echo ""
echo "=========================================="
echo "更多详细信息请查看:"
echo "  - 使用指南.md (完整中文文档)"
echo "  - README.md (官方英文文档)"
echo "  - 运行 ./train_model.sh --help 查看训练脚本帮助"
echo "=========================================="

echo ""
echo "提示: 可以直接复制上面的命令到终端中运行"
echo ""